### ISSUE TITLE
Vite 4.0.1 and "You appear to have multiple instances of Solid"

### ISSUE THREAD

**Issue by phungleson** [solidjs/solid#1426]
### Describe the bug

Hey peeps,

I am trying to upgrade my app to vite v4.0.1, however it ran into the error in header. The site cannot be loaded due to the error.

The error is clear and I understand what it means. However, I couldn't pin point which part of the app/libs caused the issue.

It would be great if someone has any thoughts how to debug this?

Thanks!

### Your Example Website or App

N/A

### Steps to Reproduce the Bug or Issue

Change to vite in `package.json` to `4.0.1` and run `vite`.

### Expected behavior

The issue should not be there and everything loads correctly.

### Screenshots or Videos

N/A

### Platform

- OS: macOS
- Browser: Chrome
- Version: 108.0.5359.98 arm

### Additional context

I am using latest of a few libs:

```
"solid-jest": "^0.2.0",
"solid-js": "^1.6.5",
"vite-plugin-solid": "^2.4.0"
"babel-preset-solid": "^1.6.2",
"solid-app-router": "^0.4.2",
```

**Comment by lxsmnsyc** [comment]
Check the lockfile for possible duplicates

**Comment by atk** [comment]
@lxsmnsyc we already found out that this is a bug introduced in the vite resolver in 4.0.1, we just haven't found the cause yet.

**Comment by itea-dev** [comment]
Today I updated my app to Vite 4 and it broke. It logs the same error as yours.

**Comment by phungleson** [comment]
This seems to be the issue in [vite #11385](https://github.com/vitejs/vite/issues/11385).

**Comment by kotx** [comment]
For me, the culprit seems to be [solid-router](https://github.com/solidjs/solid-router).

**Comment by ryansolid** [comment]
I think it would hapoen to any package that has dependencies on solid-js. Make sure there is no duplication in your node modules and if there isn't it probably something new happening due to bundling in Vite 4.

**Comment by mdynnl** [comment]
I think `vite@4.0.1` seems to be having trouble with deduping optimized dependencies. If you look at the imports on dev with optimization enabled, for any package that depends on `solid-js`, `solid-js` is directly resolved from `node_modules` while it should be resolving to optimized one. Disabling `optimizeDeps` resolves this but this might not work with some packages especially cjs only packages.

**Comment by ryansolid** [comment]
It was suggested to me that thus commit might be responsible. We should try reversing it to confirm.

https://github.com/vitejs/vite/pull/11290

**Comment by csr632** [comment]
Could anyone try this branch of vite https://github.com/csr632/vite/tree/feat/fix-resolve-optimized to test whether it is fixed?

**Comment by patak-dev** [comment]
In the meantime, we released vite@4.0.2 reverting https://github.com/vitejs/vite/pull/11290.

**Comment by csr632** [comment]
> In the meantime, we released vite@4.0.2 reverting [vitejs/vite#11290](https://github.com/vitejs/vite/pull/11290).

I can confirm that this issue is fixed in `vite@4.0.2`. Tested with this template: `npm init solid@latest`.

**Comment by itea-dev** [comment]
> In the meantime, we released vite@4.0.2 reverting [vitejs/vite#11290](https://github.com/vitejs/vite/pull/11290).

Tested vite@4.0.2 on my app and this issue is fixed.

**Comment by orenelbaum** [comment]
So I guess this issue can be closed?

**Comment by phungleson** [comment]
Yep it works fine after vite@4.0.2 upgrade, thanks everyone!

**Comment by andrezero** [comment]
Hey there 👋 

Running into this issue in a new setup (setting up a complex monorepo).

```
You appear to have multiple instances of Solid. This can lead to unexpected behavior.
```

This ☝️ shows up once per test.

I have tried all combinations of config and the issue persists. I am afraid it might be more than just noise and more complex tests .

I have [branched the repository](https://github.com/noodlestan/noodles-ui/blob/vitest-setup-issues/NOTES.md) for reproduction. sake.

Moving on with my sprint, might have more details once I start adding the actual production code.

Help appreciated 🙇

**Comment by andrezero** [comment]
Possibly related: https://github.com/solidjs/solid/discussions/1720
